spring:
  application:
    name: Auth-app-backend
  profiles:
    active: dev
  security:

    basic:
      enabled: true

server:
  port: 8083


  #configurations
  #database configurations

  #email configurations

  #oauth2 configurations
