spring:
  application:
    name: Auth-app-backend
  profiles:
    active: dev
  security:
    # Remove the user and password lines below
    basic:
      enabled: true

server:
  port: 8082


  #configurations
  #database configurations

  #email configurations

  #oauth2 configurations
